apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aitelemetry-zookeeper
spec:
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-obs/ai-telemetry/aitelemetry-zookeeper
