apiVersion: nfd.openshift.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nvidia-pci-labels-and-taints
spec:
  rules:
    - name: "NVIDIA pci-10de-<device>.present labels"
      labelsTemplate: |
        {{ range .pci.device }}pci-{{ .vendor }}-device={{ .device }}
        {{ end }}
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["10de"]}
            class: {op: In, value: ["0300", "0302"]}
    - name: "NVIDIA nvidia-gpu.product labels (Tesla-V100-PCIE-32GB)"
      labelsTemplate: |
        nvidia-gpu.product=Tesla-V100-PCIE-32GB
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["10de"]}
            class: {op: In, value: ["0302"]}
            device: {op: In, value: ["1db6"]}
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu.product
          value: Tesla-V100-PCIE-32GB
    - name: "NVIDIA nvidia-gpu.product labels (NVIDIA-A100-SXM4-40GB)"
      labelsTemplate: |
        nvidia-gpu.product=NVIDIA-A100-SXM4-40GB
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["10de"]}
            class: {op: In, value: ["0302"]}
            device: {op: In, value: ["20b0"]}
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu.product
          value: NVIDIA-A100-SXM4-40GB
    - name: "NVIDIA nvidia-gpu.product labels (NVIDIA-H100-80GB-HBM3)"
      labelsTemplate: |
        nvidia-gpu.product=NVIDIA-H100-80GB-HBM3
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["10de"]}
            class: {op: In, value: ["0302"]}
            device: {op: In, value: ["2330"]}
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu.product
          value: NVIDIA-H100-80GB-HBM3
