---
# Source: zookeeper-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-operator
  namespace: default
  labels:
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/version: "0.2.14"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: "zookeeper-operator-0.2.14"
---
# Source: zookeeper-operator/templates/post-install-upgrade-hooks.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-operator-post-install-upgrade
  namespace: default
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
---
# Source: zookeeper-operator/templates/pre-delete-hooks.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-operator-pre-delete
  namespace: default
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
