apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: prom-keycloak-proxy
      deployment: prom-keycloak-proxy-open-sovereign-ai-cloud
    includeSelectors: true

nameSuffix: -open-sovereign-ai-cloud

resources:
  - ../../../base

patches:
  - patch: |
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: prom-keycloak-proxy-certs
      spec:
        target:
          name: prom-keycloak-proxy-certs-open-sovereign-ai-cloud
        dataFrom:
        - extract:
            key: nerc/nerc-ocp-obs/prom-keycloak-proxy/open-sovereign-ai-cloud/certs
  - patch: |
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: prom-keycloak-proxy-secrets
      spec:
        target:
          name: prom-keycloak-proxy-secrets-open-sovereign-ai-cloud
        dataFrom:
        - extract:
            key: nerc/nerc-ocp-obs/prom-keycloak-proxy/open-sovereign-ai-cloud/secrets
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: prom-keycloak-proxy
      spec:
        template:
          spec:
            containers:
            - name: prom-keycloak-proxy
              env:
                - name: PROXY_ACM_HUB
                  value: open-sovereign-ai-cloud
              envFrom:
                - secretRef:
                    name: prom-keycloak-proxy-secrets-open-sovereign-ai-cloud
            volumes:
              - name: prom-keycloak-proxy-certs
                secret:
                  secretName: prom-keycloak-proxy-certs-open-sovereign-ai-cloud
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: prom-keycloak-proxy
      spec:
        selector:
          app: prom-keycloak-proxy
          deployment: prom-keycloak-proxy-open-sovereign-ai-cloud
  - patch: |
      kind: Route
      apiVersion: route.openshift.io/v1
      metadata:
        name: prom-keycloak-proxy
      spec:
        host: metrics-open-sovereign-ai-cloud.apps.obs.nerc.mghpcc.org
        to:
          name: prom-keycloak-proxy-open-sovereign-ai-cloud
