apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namesapce: openshift-config
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: github-client-secret
  data:
  - secretKey: clientSecret
    remoteRef:
      key: nerc/nerc-ocp-infra/openshift-config/github-client-secret
      property: clientSecret
