apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      nerc.mghpcc.org/bundle: acm-observability
      nerc.mghpcc.org/kustomized: "true"
resources:
  - ../../base/core/namespaces/open-cluster-management-observability
