apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acm-metrics
  namespace: open-cluster-management-observability
spec:
  data:
  - secretKey: bucket
    remoteRef:
      key: nerc/hypershift2/open-cluster-management-observability/acm-metrics
      property: bucket
  - secretKey: endpoint
    remoteRef:
      key: nerc/hypershift2/open-cluster-management-observability/acm-metrics
      property: endpoint
  - secretKey: access_key
    remoteRef:
      key: nerc/hypershift2/open-cluster-management-observability/acm-metrics
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: nerc/hypershift2/open-cluster-management-observability/acm-metrics
      property: secret_key
