kind: ConfigMap
apiVersion: v1
metadata:
  name: dns-config
  namespace: custom-dns
data:
  Corefile: |
    infra.nerc.mghpcc.org:8053 {
        log stdout
        file /etc/coredns/infra.nerc.mghpcc.org
    }
  infra.nerc.mghpcc.org: |
    $TTL    1800
    $ORIGIN infra.nerc.mghpcc.org.

    @ IN SOA dns domains (
        2020031101   ; serial
        300          ; refresh
        1800         ; retry
        14400        ; expire
        300 )        ; minimum

    api        IN  A  10.30.9.5
    *.apps     IN  A  10.30.9.6
