apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  name: default
spec:
  servers:
  - name: nerc-ocp-infra
    zones:
    - infra.nerc.mghpcc.org
    forwardPlugin:
      policy: Random
      upstreams:
      - <service-ip>:8053
