apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: custom-dns
spec:
  ports:
  - name: 8053-tcp
    port: 8053
    protocol: TCP
    targetPort: 8053
  - name: 8053-udp
    port: 8053
    protocol: UDP
    targetPort: 8053
  selector:
    app: dns
    deployment: dns
