apiVersion: v1
kind: Service
metadata:
  name: custom-dns
  namespace: custom-dns
spec:
  ports:
  - name: dns-tcp
    port: 8053
    protocol: TCP
    targetPort: dns-tcp
  - name: dns-udp
    port: 8053
    protocol: UDP
    targetPort: dns-udp
