apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
spec:
  deployment:
    envFrom:
      - secretRef:
          name: oauth-client-secret
      - secretRef:
          name: grafana-serviceaccount-token
      - configMapRef:
          name: openshift-service-ca.crt
  config:
    server:
      root_url: https://grafana.apps.infra.nerc.mghpcc.org
    auth.generic_oauth:
      enabled: true
      scopes: openid email groups profile
      email_attribute_path: name
      api_url: https://dex-dex.apps.infra.nerc.mghpcc.org/userinfo
      auth_url: https://dex-dex.apps.infra.nerc.mghpcc.org/auth
      token_url: https://dex-dex.apps.infra.nerc.mghpcc.org/token
      role_attribute_path: >-
        contains(groups[*], 'cluster-admins') && 'Admin' ||
        contains(groups[*], 'nerc-org-admins')  && 'Admin' ||
        contains(groups[*], 'nerc-ops')   && 'Editor' ||
        'Deny'
      role_attribute_strict: true
      client_id: grafana
