auth:
- type: kubernetes
  path: kubernetes/nerc-ocp-edu
  config:
    kubernetes_ca_cert: "${ file `certs/letsencrypt.crt` }"
    kubernetes_host: https://api.edu.nerc.mghpcc.org:6443
    token_reviewer_jwt: "${ file `creds/nerc-ocp-edu-token-reviewer` }"
  roles:
  - bound_service_account_names:
    - vault-secret-reader
    bound_service_account_namespaces:
    - openshift-storage
    - group-sync-operator
    - openshift-config
    - openshift-ingress
    - openshift-logging
    - openshift-ingress-operator
    - rhods-notebooks
    name: secret-reader
    policies:
    - nerc-common-reader
    - nerc-ocp-edu-reader
policies:
- name: nerc-ocp-edu-reader
  rules: |
    path "nerc/data/nerc-ocp-edu/*" {
      capabilities = ["read"]
    }
