apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  name: default
spec:
  cache:
    negativeTTL: 30s
    positiveTTL: 900s
  logLevel: Normal
  operatorLogLevel: Normal
  upstreamResolvers:
    policy: Sequential
    protocolStrategy: ""
    upstreams:
    - port: 53
      type: SystemResolvConf
  servers:
  - name: nerc-infra
    zones:
    - nerc-ocp-infra.rc.fas.harvard.edu
    forwardPlugin:
      policy: Random
      upstreams:
      - custom-dns.custom-dns.svc.cluster.local:8053
