apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: metrics-backing-store
  namespace: openshift-storage
spec:
  pvPool:
    numVolumes: 6
    resources:
      requests:
        storage: 400Gi
    storageClass: ocs-external-storagecluster-ceph-rbd
  type: pv-pool
