apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/core/namespaces/aap
- ../../base/operators.coreos.com/operatorgroups/aap
- ../../base/operators.coreos.com/subscriptions/ansible-automation-platform-operator
labels:
- includeSelectors: true
  pairs:
    nerc.mghpcc.org/bundle: ansible-automation-platform-operator
