apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - verbs:
      - '*'
    apiGroups:
      - app.k8s.io
    resources:
      - applications
