apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moc-metrics-collector
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  - prometheuses/api
  verbs:
  - get
  - list
