apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-storage

components:
  - ../../../../components/nerc-secret-store

resources:
  - ../../../../bundles/odf-external
  - externalsecrets/rook-ceph-external-cluster-details.yaml
  - redhatcop.redhat.io/odf-node-patcher.yaml

patches:
  - path: storageclasses/ocs-external-storagecluster-ceph-rbd_patch.yaml
  - path: subscriptions/subscription_patch.yaml
