apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-group-sync
  namespace: group-sync-operator
spec:
  secretStoreRef:
    name: nerc-secret-store
    kind: SecretStore
  target:
    name: github-group-sync
  data:
  - secretKey: appId
    remoteRef:
      key: nerc/virt/group-sync-operator/github-group-sync-token
      property: appId
  - secretKey: privateKey
    remoteRef:
      key: nerc/virt/group-sync-operator/github-group-sync-token
      property: privateKey
