apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moc-metrics-collector-binding
subjects:
- kind: ServiceAccount
  name: moc-metrics-collector
  namespace: moc-metrics-collector
roleRef:
  kind: ClusterRole
  name: moc-metrics-collector
  apiGroup: rbac.authorization.k8s.io
