apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    nerc.mghpcc.org/aggregate-to-nerc-ops: "true"
  name: opendatahub-nerc-ops
rules:
  - apiGroups:
      - dashboard.opendatahub.io
    resources:
      - '*'
    verbs:
      - list
      - get
      - watch
