apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: vault
spec:
  vaultEnvsConfig:
  - name: SKIP_CHOWN
    value: "1"
  - name: SKIP_SETCAP
    value: "1"
  size: 3
  image: docker.io/hashicorp/vault:1.20.0

  serviceAccount: vault
  serviceType: ClusterIP

  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/data

  unsealConfig:
    options:
      preFlightChecks: true
      storeRootToken: true
      secretShares: 5
      secretThreshold: 3
    kubernetes:
      secretNamespace: default

  config:
    disable_mlock: true
    storage:
      raft:
        path: "/vault/data"
    listener:
    - tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key

    # This listener is used by the OpenShift route.
    - tcp:
        address: "0.0.0.0:8300"
        tls_disable: "true"
    api_addr: https://vault.vault:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    ui: true

  statsdDisabled: true
  serviceRegistrationEnabled: true

  resources:
    vault:
      limits:
        memory: "512Mi"
        cpu: "200m"
      requests:
        memory: "256Mi"
        cpu: "100m"
