{
 "title": "Blocked MachineConfigUpdate",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "mco_unavailable_machine_count by cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mco_unavailable_machine_count) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mco_degraded_machine_count by cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mco_degraded_machine_count) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mco_machine_count by cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mco_machine_count) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count vs updated vs unavailable vs degraded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mco_machine_count)", "legendFormat": "__auto" },
    { "expr": "sum(mco_updated_machine_count)", "legendFormat": "__auto" },
    {
     "expr": "sum(mco_unavailable_machine_count)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mco_degraded_machine_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}