{
 "title": "AI Model Performance",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "llm_performance_response_time", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "llm_performance_latency", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Throughput (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "llm_performance_throughput", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Power Usage (watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Inter-token Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "llm_performance_itl", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "GPU Memory Copy Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    { "expr": "DCGM_FI_DEV_MEM_COPY_UTIL", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Nodes with unhealthy GPUs",
   "type": "timeseries",
   "description": "Autopilot labeled nodes with unhealthy GPUs",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_node_labels{label_autopilot_ibm_com_gpuhealth=~\".*ERR.*\"} and kube_node_labels{label_autopilot_ibm_com_gpuhealth!~\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes with Low PCIe Bandwidth (<3.4 GB/s)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(autopilot_health_checks{health=~\"pciebw\"}[12h])) by (node, deviceid) < 3.4 "
    }
   ]
  },
  {
   "title": "GPU Temperature (F)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_TEMP)" }
   ]
  }
 ]
}