{
 "title": "OPE metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "used in % of limits",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"limits.cpu\",type=\"used\"}[10m:5m])) / sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"limits.cpu\",type=\"hard\"}[10m:5m])) * 100",
     "legendFormat": "cpu in % of limits"
    },
    {
     "expr": "sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"limits.ephemeral-storage\",type=\"used\"}[10m:5m])) / sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"limits.ephemeral-storage\",type=\"hard\"}[10m:5m])) * 100",
     "legendFormat": "ephemeral-storage in % of limits"
    },
    {
     "expr": "sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"limits.memory\",type=\"used\"}[10m:5m])) / sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"limits.memory\",type=\"hard\"}[10m:5m])) * 100",
     "legendFormat": "memory in % of limits"
    },
    {
     "expr": "sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"persistentvolumeclaims\",type=\"used\"}[10m:5m])) / sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"persistentvolumeclaims\",type=\"hard\"}[10m:5m])) * 100",
     "legendFormat": "persistentvolumeclaims  in % of limits"
    },
    {
     "expr": "sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"requests.storage\",type=\"used\"}[10m:5m])) / sum(avg_over_time(kube_resourcequota{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\",resource=\"requests.storage\",type=\"hard\"}[10m:5m])) * 100",
     "legendFormat": "requests.storage in % of limits"
    }
   ]
  },
  {
   "title": "pods-owner and container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\"})",
     "legendFormat": "container"
    },
    {
     "expr": "count(kube_pod_owner{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\"})",
     "legendFormat": "pod owner"
    }
   ]
  },
  {
   "title": "container per pods-owner",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\"}) / count(kube_pod_owner{cluster=\"nerc-ocp-prod\",namespace=\"rhods-notebooks\"})",
     "legendFormat": "container"
    }
   ]
  }
 ]
}