apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-billing-credentials
  namespace: metering-thor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: clickhouse-billing-credentials
    template:
      type: Opaque
  data:
  - secretKey: password
    remoteRef:
      key: nerc/nerc-ocp-test/metering-thor/clickhouse-billing-credentials
      property: password
