apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-ruler-custom-rules
  namespace: open-cluster-management-observability
data:
  custom_rules.yaml: |
    groups:
      {{ range $path, $_ := .Files.Glob "rules/**.yaml" }}
      {{ $.Files.Get $path | nindent 6 }}
      {{ end }}
