apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    name: version
  spec:
    channel: stable-4.19
    clusterID: 7bbde55c-9a5f-46e0-9270-5c1cea1e7300
kind: List
metadata: {}
