apiVersion: keycloak.nerc.mghpcc.org/v1
kind: KeycloakAuthorization
metadata:
  name: nerc
  labels:
    app: keycloak
    realm: NERC
spec:
  cleanupUndefinedAuthorizations: true
  keycloak:
    baseUrl: https://keycloak.apps.obs.nerc.mghpcc.org
    adminSecret:
      name: keycloak-initial-admin
      usernameKey: username
      passwordKey: password
  realm:
    id: NERC
    clients:
      - id: nerc
        authorizationSettings:
          scopes:

            - id: namespace-all
              name: all namespaces
              displayName: all namespaces
            - id: namespace-rhods-notebooks
              name: rhods-notebooks
              displayName: rhods-notebooks namespace
            - id: namespace-kruizeoptimization-143c8e
              name: kruizeoptimization-143c8e
              displayName: kruizeoptimization-143c8e namespace
            - id: namespace-kruizeoptimization-5ad5bc
              name: kruizeoptimization-5ad5bc
              displayName: kruizeoptimization-5ad5bc namespace

            - id: cluster-all
              name: all clusters
              displayName: all clusters
            - id: cluster-nerc-ocp-infra
              name: nerc-ocp-infra
              displayName: nerc-ocp-infra cluster
            - id: cluster-nerc-ocp-obs
              name: nerc-ocp-obs
              displayName: nerc-ocp-obs cluster
            - id: cluster-nerc-ocp-prod
              name: nerc-ocp-prod
              displayName: nerc-ocp-prod cluster
            - id: cluster-nerc-ocp-test
              name: nerc-ocp-test
              displayName: nerc-ocp-test cluster

          resources:
            - name: cluster
              displayName: cluster
              scopes:
                - id: cluster-all
                  name: all clusters
                  displayName: all clusters
                - id: cluster-nerc-ocp-infra
                  name: nerc-ocp-infra
                  displayName: nerc-ocp-infra cluster
                - id: cluster-nerc-ocp-obs
                  name: nerc-ocp-obs
                  displayName: nerc-ocp-obs cluster
                - id: cluster-nerc-ocp-prod
                  name: nerc-ocp-prod
                  displayName: nerc-ocp-prod cluster
                - id: cluster-nerc-ocp-test
                  name: nerc-ocp-test
                  displayName: nerc-ocp-test cluster

            - name: namespace
              displayName: namespace
              scopes:
                - id: namespace-all
                  name: all namespaces
                  displayName: all namespaces
                - id: namespace-rhods-notebooks
                  name: rhods-notebooks
                  displayName: rhods-notebooks namespace
                - id: namespace-kruizeoptimization-143c8e
                  name: kruizeoptimization-143c8e
                  displayName: kruizeoptimization-143c8e namespace
                - id: namespace-kruizeoptimization-5ad5bc
                  name: kruizeoptimization-5ad5bc
                  displayName: kruizeoptimization-5ad5bc namespace

          policies:

            - id: group-nerc-ops
              name: group-nerc-ops
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                group:
                  groups:
                    - id: nerc-ops

            - id: group-ai-telemetry
              name: group-ai-telemetry
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                group:
                  groups:
                    - id: ai-telemetry

            - id: client-ai-telemetry
              name: client-ai-telemetry
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                client:
                  clients:
                    - ai-telemetry

            - id: client-ai-telemetry-sa
              name: client-ai-telemetry-sa
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                client:
                  clients:
                    - ai-telemetry-sa

            - id: client-ai4cloudops
              name: client-ai4cloudops
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                client:
                  clients:
                    - ai4cloudops
            - id: group-nerc-ai4cloudops
              name: group-nerc-ai4cloudops
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                group:
                  groups:
                    - id: nerc-ai4cloudops

            - id: client-oct
              name: client-oct
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                client:
                  clients:
                    - oct

            - id: client-kruizeoptimization
              name: client-kruizeoptimization
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type:
                client:
                  clients:
                    - kruizeoptimization

          permissions:

            - name: group-nerc-ops-cluster-all
              policy: group-nerc-ops
              resource: cluster
            - name: group-nerc-ops-namespace-all
              policy: group-nerc-ops
              resource: namespace

            - name: group-ai-telemetry-cluster-all
              policy: group-ai-telemetry
              resource: cluster
            - name: group-ai-telemetry-namespace-all
              policy: group-ai-telemetry
              resource: namespace

            - name: client-ai-telemetry-sa-cluster-all
              policy: client-ai-telemetry-sa
              resource: cluster
            - name: client-ai-telemetry-sa-namespace-all
              policy: client-ai-telemetry-sa
              resource: namespace

            - name: group-nerc-ai4cloudops-namespace-all
              policy: group-nerc-ai4cloudops
              resource: namespace
            - name: client-ai4cloudops-namespace-all
              policy: client-ai4cloudops
              resource: namespace
            - name: group-nerc-ai4cloudops-cluster-nerc-ocp-prod
              policy: group-nerc-ai4cloudops
              resource: cluster
              scope: nerc-ocp-prod
            - name: client-ai4cloudops-cluster-nerc-ocp-prod
              policy: client-ai4cloudops
              resource: cluster
              scope: nerc-ocp-prod

            - name: client-oct-namespace-all
              policy: client-oct
              resource: namespace
            - name: client-oct-cluster-all
              policy: client-oct
              resource: cluster

            - name: client-kruizeoptimization-cluster-nerc-ocp-prod
              policy: client-kruizeoptimization
              resource: cluster
              scope: nerc-ocp-prod
            - name: client-kruizeoptimization-namespace-kruizeoptimization-143c8e
              policy: client-kruizeoptimization
              resource: namespace
              scope: kruizeoptimization-143c8e
            - name: client-kruizeoptimization-namespace-kruizeoptimization-5ad5bc
              policy: client-kruizeoptimization
              resource: namespace
              scope: kruizeoptimization-5ad5bc
