apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ibm-spectrum-scale-webhook-service-cert
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: operator
  name: ibm-spectrum-scale-webhook-service
  namespace: ibm-spectrum-scale-operator
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: operator
    control-plane: controller-manager
