apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autopilot-privileged
  namespace: autopilot
subjects:
- kind: ServiceAccount
  name: autopilot
  namespace: autopilot
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
