apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-route53-credentials
  namespace: openshift-operators
spec:
  secretStoreRef:
    kind: SecretStore
    name: nerc-secret-store
  target:
    name: aws-route53-credentials
    # Prevent generated Secret from inheriting the labels from this
    # ExternalSecret. OpenShift will create a copy of the Secret, and the
    # labels will causse it to show up as out-of-sync in ArgoCD. See
    # https://github.com/OCP-on-NERC/operations/issues/42 for additional
    # details.
    template:
      metadata:
        labels: {}
  dataFrom:
    - extract:
        key: REPLACE_IN_OVERLAY
