apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: operator
  name: ibm-spectrum-scale-restricted
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ibm-spectrum-scale-restricted
  resources:
  - securitycontextconstraints
  verbs:
  - use
