apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: operator
  name: ibm-spectrum-scale-regional-dr
rules:
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - asyncreplications
  - consistencygroups
  - regionaldrs
  verbs:
  - get
  - list
  - watch
