apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-cluster-management-observability-acm-metrics-2ti-object-storage
  namespace: open-cluster-management-observability
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: acm-metrics-2ti-object-storage
    template:
      type: Opaque
      engineVersion: v2
      data:
        acm-metrics-2ti.yaml: |
          type: s3
          config:
            bucket: "{{ .bucket }}"
            endpoint: "{{ .endpoint }}"
            insecure: false
            access_key: "{{ .access_key }}"
            secret_key: "{{ .secret_key }}"
  data:
  - secretKey: bucket
    remoteRef:
      key: UPDATE_IN_OVERLAY    # the path-details will be replaced in the overlay patch
      property: bucket
  - secretKey: endpoint
    remoteRef:
      key: UPDATE_IN_OVERLAY
      property: endpoint
  - secretKey: access_key
    remoteRef:
      key: UPDATE_IN_OVERLAY
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: UPDATE_IN_OVERLAY
      property: secret_key
