apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snmp-exporter
commonLabels:
  app: snmp-exporter

resources:
  - deployment-prometheus-snmp-exporter.yaml
  - role-prometheus-snmp-exporter.yaml
  - rolebinding-prometheus-snmp-exporter.yaml
  - service-prometheus-snmp-exporter.yaml
  - serviceaccount-prometheus-snmp-exporter.yaml
  - servicemonitor-prometheus-snmp-exporter-vlan-935-moc-swmon.yaml

configMapGenerator:
- name: snmp-generator-config
  options:
    disableNameSuffixHash: true
  files:
  - files/generator.yml

- name: observability-metrics-custom-allowlist
  options:
    disableNameSuffixHash: true
  files:
  - files/uwl_metrics_list.yaml
