---
# Source: prometheus-snmp-exporter/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: prometheus-snmp-exporter
  labels:
    helm.sh/chart: prometheus-snmp-exporter-6.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-snmp-exporter
    app.kubernetes.io/name: prometheus-snmp-exporter
    app.kubernetes.io/instance: prometheus-snmp-exporter
    app.kubernetes.io/version: "v0.27.0"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9116
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus-snmp-exporter
    app.kubernetes.io/instance: prometheus-snmp-exporter
