---
# Source: prometheus-snmp-exporter/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-snmp-exporter-vlan-935-moc-swmon
  namespace: snmp-exporter
  labels:
    helm.sh/chart: prometheus-snmp-exporter-6.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-snmp-exporter
    app.kubernetes.io/name: prometheus-snmp-exporter
    app.kubernetes.io/instance: prometheus-snmp-exporter
    app.kubernetes.io/version: "v0.27.0"
    prometheus: "kube-prometheus"
spec:
  endpoints:
    - port: http
      honorLabels: true
      path: /snmp
      scrapeTimeout: 10s
      params:
        module: [if_mib]
        auth: [public_v2]
        target:
          - 10.82.3.41
      metricRelabelings:
        - sourceLabels: [instance]
          targetLabel: instance
          replacement: 10.82.3.41
          action: replace
        - sourceLabels: [target]
          targetLabel: target
          replacement: vlan-935-moc-swmon
          action: replace
  jobLabel: "prometheus-snmp-exporter"
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-snmp-exporter
      app.kubernetes.io/instance: prometheus-snmp-exporter
