apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-api-certificate
  namespace: openshift-config
spec:
  issuerRef:
    name: letsencrypt-production-dns01
    kind: Issuer
  secretName: default-api-certificate
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
    - "api.albany.nerc.mghpcc.org"
