apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/operators.coreos.com/subscriptions/mongodb-operator
labels:
- includeSelectors: true
  pairs:
    nerc.mghpcc.org/bundle: mongodb-operator
