apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- externalsecrets
- lokistacks
- clusterroles
- clusterrolebindings
- uiplugins
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: lokistack
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: cluster-logging
