apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gpu-taint-management

resources:
  - deployment.yaml
  - sa.yaml
  - namespace.yaml
  - clusterrolebinding.yaml
  - clusterrole.yaml

configMapGenerator:
  - name: gpu-product-taint-script
    files:
      - taint.sh

generatorOptions:
  disableNameSuffixHash: true
