apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  driver:
    upgradePolicy:
      autoUpgrade: true
    version: "580.105.08"
    repository: "nvcr.io/nvidia"
    image: "driver"
  daemonsets:
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: NVIDIA-A100-SXM4-40GB
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: Tesla-V100-PCIE-32GB
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: NVIDIA-H100-80GB-HBM3
