apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: ibm-spectrum-scale-regional-dr
  namespace: ibm-spectrum-scale
rules:
- apiGroups:
  - ""
  resourceNames:
  - stunnel
  resources:
  - secrets
  verbs:
  - get
