apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: virt
resources:
  - ../../base/core/namespaces/openshift-cnv
  - ../../base/operators.coreos.com/operatorgroups/kubevirt-hyperconverged
  - ../../base/operators.coreos.com/subscriptions/kubevirt-hyperconverged
