apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nerc-backup-wasabi
resources:
  - namespace.yaml
  - externalsecrets
  - cronjobs
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: nerc-backup-wasabi
      app.kubernetes.io/part-of: nerc-s3-offsite-backup
