apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zookeeper
labels:
  - includeSelectors: true
    pairs:
      app: persistent-metrics-zookeeper
      deployment: persistent-metrics-zookeeper

resources:
  - deployments/
  - services/
