apiVersion: v1
imagePullSecrets:
- name: ibm-entitlement-key
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: operator
  name: ibm-spectrum-scale-operator
  namespace: ibm-spectrum-scale-operator
