apiVersion: v1
automountServiceAccountToken: false
imagePullSecrets:
- name: ibm-entitlement-key
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: ibm-spectrum-scale-gui
  namespace: ibm-spectrum-scale
