apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: prom-keycloak-proxy
      deployment: prom-keycloak-proxy-innabox-dev
    includeSelectors: true

nameSuffix: -innabox-dev

resources:
  - ../../../base

patches:
  - patch: |
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: prom-keycloak-proxy-certs
      spec:
        target:
          name: prom-keycloak-proxy-certs-innabox-dev
        dataFrom:
        - extract:
            key: nerc/nerc-ocp-obs/prom-keycloak-proxy/innabox-dev/certs
  - patch: |
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: prom-keycloak-proxy-secrets
      spec:
        target:
          name: prom-keycloak-proxy-secrets-innabox-dev
        dataFrom:
        - extract:
            key: nerc/nerc-ocp-obs/prom-keycloak-proxy/innabox-dev/secrets
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: prom-keycloak-proxy
      spec:
        template:
          spec:
            containers:
            - name: prom-keycloak-proxy
              env:
                - name: PROXY_ACM_HUB
                  value: innabox-dev
              envFrom:
                - secretRef:
                    name: prom-keycloak-proxy-secrets-innabox-dev
            volumes:
              - name: prom-keycloak-proxy-certs
                secret:
                  secretName: prom-keycloak-proxy-certs-innabox-dev
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: prom-keycloak-proxy
      spec:
        selector:
          app: prom-keycloak-proxy
          deployment: prom-keycloak-proxy-innabox-dev
  - patch: |
      kind: Route
      apiVersion: route.openshift.io/v1
      metadata:
        name: prom-keycloak-proxy
      spec:
        host: metrics-innabox-dev.apps.obs.nerc.mghpcc.org
        to:
          name: prom-keycloak-proxy-innabox-dev
