---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: custom-login-templates
  namespace: openshift-config
spec:
  data:
  - remoteRef:
      key: REPLACE_IN_OVERLAY
      property: providers.html
    secretKey: providers.html
  secretStoreRef:
    kind: SecretStore
    name: nerc-secret-store
  target:
    name: custom-login-templates
    template:
      metadata:
        labels: {}
