apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: acm
spec:
    channel: release-2.13
    installPlanApproval: Automatic
    name: advanced-cluster-management
    source: redhat-operators
    sourceNamespace: openshift-marketplace
