apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default-api-certificate
  namespace: openshift-config
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: default-api-certificate
    template:
      type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-prod/openshift-api/default-api-certificate
