apiVersion: infrastructure.opendatahub.io/v1alpha1
kind: HardwareProfile
metadata:
  annotations:
    opendatahub.io/dashboard-feature-visibility: '[]'
    opendatahub.io/disabled: "false"
    opendatahub.io/display-name: Large
    opendatahub.io/modified-date: "2026-01-06T19:33:57.323Z"
  name: large
  namespace: redhat-ods-applications
spec:
  identifiers:
  - defaultCount: "7"
    displayName: CPU
    identifier: cpu
    maxCount: "14"
    minCount: 1
    resourceType: CPU
  - defaultCount: 56Gi
    displayName: Memory
    identifier: memory
    maxCount: 56Gi
    minCount: 2Gi
    resourceType: Memory
