apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: costmanagement-metrics-operator
resources:
  - ../../base/core/namespaces/costmanagement-metrics-operator/
  - ../../base/operators.coreos.com/operatorgroups/costmanagement-metrics-operator/
  - ../../base/operators.coreos.com/subscriptions/costmanagement-metrics-operator/
