issuer: https://dex-dex.apps.infra.nerc.mghpcc.org

storage:
  type: memory

web:
  http: "0.0.0.0:5556"

grpc:
  addr: "0.0.0.0:5557"

telemetry:
  http: "0.0.0.0:5558"

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: vault
    name: Vault
    redirectURIs:
      - https://vault.apps.infra.nerc.mghpcc.org/oidc/callback
      - https://vault.apps.infra.nerc.mghpcc.org/ui/vault/auth/oidc/oidc/callback
      - https://vault-ui-vault.apps.infra.nerc.mghpcc.org/oidc/callback
      - https://vault-ui-vault.apps.infra.nerc.mghpcc.org/ui/vault/auth/oidc/oidc/callback
    secretEnv: VAULT_SECRET
  - id: grafana
    name: Grafana
    redirectURIs:
      - https://logging-grafana.apps.infra.nerc.mghpcc.org/login/generic_oauth
      - https://grafana.apps.infra.nerc.mghpcc.org/login/generic_oauth
    secretEnv: GRAFANA_SECRET

connectors:
  - type: openshift
    id: openshift
    name: OpenShift
    config:
      issuer: https://kubernetes.default.svc
      clientID: system:serviceaccount:dex:dex
      clientSecret: $OPENSHIFT_CLIENT_SECRET
      redirectURI: https://dex-dex.apps.infra.nerc.mghpcc.org/callback
      groups:
        - system:authenticated
