apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer
  namespace: grafana
  labels:
    app: grafana-image-renderer
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: grafana-image-renderer
  type: ClusterIP
