apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-image-renderer
  namespace: grafana
  labels:
    app: grafana-image-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-image-renderer
  template:
    metadata:
      labels:
        app: grafana-image-renderer
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: grafana-image-renderer
          image: grafana/grafana-image-renderer:3.11.3
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          env:
            - name: BROWSER_TZ
              value: UTC
            - name: ENABLE_METRICS
              value: 'true'
            - name: HTTP_PORT
              value: '8081'
          envFrom:
            - secretRef:
                name: grafana-renderer-token
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
