apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana.yaml
  - grafana-image-renderer-deployment.yaml
  - grafana-image-renderer-service.yaml
  - grafana-image-renderer-networkpolicy.yaml
