apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: metering
  namespace: metering-thor
spec:
  configuration:
    clusters:
    - name: metering
      layout:
        shardsCount: 1
        replicasCount: 1
  defaults:
    templates:
      podTemplate: clickhouse-pod
      dataVolumeClaimTemplate: clickhouse-data
  templates:
    podTemplates:
    - name: clickhouse-pod
      spec:
        containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.3
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
    volumeClaimTemplates:
    - name: clickhouse-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 50Gi
