apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: billing-events
  namespace: metering-thor
  labels:
    strimzi.io/cluster: metering
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: billing-events-dlq
  namespace: metering-thor
  labels:
    strimzi.io/cluster: metering
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 2592000000
    cleanup.policy: delete
