apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: metering-otel-collector
  namespace: metering-thor
  labels:
    strimzi.io/cluster: metering-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: billing-events
        operations:
          - Write
          - Describe
      - resource:
          type: transactionalId
          name: otel-collector
        operations:
          - Describe
          - Write
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: metering-reconciler
  namespace: metering-thor
  labels:
    strimzi.io/cluster: metering-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: billing-events
        operations:
          - Write
          - Describe
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: metering-stream-processor
  namespace: metering-thor
  labels:
    strimzi.io/cluster: metering-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: billing-events
        operations:
          - Read
          - Describe
      - resource:
          type: group
          name: stream-processor
        operations:
          - Read
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: metering-openmeter
  namespace: metering-thor
  labels:
    strimzi.io/cluster: metering-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: billing-events
        operations:
          - Read
          - Describe
      - resource:
          type: group
          name: openmeter-consumer
        operations:
          - Read
