apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metering-thor
commonLabels:
  app.kubernetes.io/part-of: metering

resources:
- kafka.yaml
- kafkatopics.yaml
- kafkausers.yaml
- rbac.yaml
- reconciler-cronjob.yaml
- externalsecrets
- clickhouse.yaml
- clickhouse-schema-configmap.yaml
- clickhouse-schema-job.yaml
- stream-processor.yaml
- openmeter-config.yaml
- openmeter.yaml
