apiVersion: v1
kind: ServiceAccount
metadata:
  name: metering-reconciler
  namespace: metering-thor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metering-reconciler
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "persistentvolumeclaims", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metering-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metering-reconciler
subjects:
- kind: ServiceAccount
  name: metering-reconciler
  namespace: metering-thor
