apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nagios:monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nagios:monitoring
subjects:
- kind: ServiceAccount
  name: nagios-monitor
  namespace: nagios
