apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: nerc-cluster-secrets
spec:
  provider:
    vault:
      server: "https://vault-ui-vault.apps.infra.nerc.mghpcc.org/"
      auth:
        kubernetes:
          mountPath: kubernetes/hypershift2
          role: secret-reader
          serviceAccountRef:
            name: "vault-secret-reader"
