apiVersion: v1
kind: Service
metadata:
  labels:
    app: autopilot
    service: autopilot-readinessprobe
  name: autopilot-readinessprobe
  namespace: autopilot
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: readinessprobe
  selector:
    app: autopilot
