apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weka-client-privileged
  namespace: weka-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: weka-client
  namespace: weka-operator-system
