apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  name: nvidia-v100-gpu
  namespace: redhat-ods-applications
spec:
  displayName: NVIDIA V100 GPU
  enabled: true
  identifier: nvidia.com/gpu
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: Tesla-V100-PCIE-32GB
