apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: object-bucket-class
  namespace: openshift-storage
spec:
  placementPolicy:
    tiers:
    - backingStores:
      - object-backing-store
