apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/core/namespaces/strimzi-kafka-operator
- ../../base/operators.coreos.com/operatorgroups/strimzi-kafka-operator
- ../../base/operators.coreos.com/subscriptions/strimzi-kafka-operator
labels:
- includeSelectors: true
  pairs:
    nerc.mghpcc.org/bundle: strimzi-kafka-operator
