apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: v100-flavor
spec:
  tolerations:
    - key: "nvidia.com/gpu.product"
      operator: "Equal"
      value: "Tesla-V100-PCIE-32GB"
      effect: "NoSchedule"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: a100-flavor
spec:
  tolerations:
    - key: "nvidia.com/gpu.product"
      operator: "Equal"
      value: "NVIDIA-A100-SXM4-40GB"
      effect: "NoSchedule"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: h100-flavor
spec:
  tolerations:
    - key: "nvidia.com/gpu.product"
      operator: "Equal"
      value: "NVIDIA-H100-80GB-HBM3"
      effect: "NoSchedule"
