apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: v100-clusterqueue
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu", "cpu", "memory"]
      flavors:
        - name: "v100-flavor"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 3
            - name: "cpu"
              nominalQuota: 20
            - name: "memory"
              nominalQuota: 50Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: a100-clusterqueue
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu", "cpu", "memory"]
      flavors:
        - name: "a100-flavor"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 0
            - name: "cpu"
              nominalQuota: 20
            - name: "memory"
              nominalQuota: 50Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: h100-clusterqueue
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu", "cpu", "memory"]
      flavors:
        - name: "h100-flavor"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 0
            - name: "cpu"
              nominalQuota: 20
            - name: "memory"
              nominalQuota: 50Gi
