apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# See https://rcarrata.com/openshift/argo-and-acm/

resources:
- ../../base
- gitopscluster/argocd-managed.yaml
- managedclustersetbindings/argocd-managed.yaml
- managedclustersets/argocd-managed.yaml
- placements/argocd-managed.yaml
- clusters
labels:
- includeSelectors: true
  pairs:
    nerc.mghpcc.org/kustomized: "true"
