# Continue to service the old route so that we don't need to update
# all of our SecretStore manifests.
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vault-compat
spec:
  host: vault-ui-vault.apps.infra.nerc.mghpcc.org
  port:
    targetPort: api-port
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: vault-ingress
