apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
    - apiGroups:
      - "internal.open-cluster-management.io"
      kinds:
      - "ManagedClusterInfo"
      clusters:
      - "*"
  rbac:
    policy: |
      p, role:operator, applications, sync, */*, allow
      p, role:operator, applications, update, */*, allow

      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, nerc-ops, role:operator
    scopes: '[groups]'
