apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # pin the Vault paths to this cluster ($ENV/$CLUSTER -> nerc/nerc-ocp-obs)
  - patch: |
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: nerc-s3-creds
      spec:
        dataFrom:
          - extract:
              key: nerc/nerc-ocp-obs/loki-thanos-object-storage
  - patch: |
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: wasabi-creds
      spec:
        dataFrom:
          - extract:
              key: nerc/nerc-ocp-obs/wasabi-backup
