apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: odf-node-label-workers
  namespace: openshift-storage
spec:
  serviceAccountRef:
    name: patcher
  patches:
    odf-node-label-workers:
      targetObjectRef:
        apiVersion: v1
        kind: Node
        labelSelector:
          matchLabels:
            node-role.kubernetes.io/worker: ""
      patchType: application/strategic-merge-patch+json
      patchTemplate: |
        metadata:
          labels:
            "cluster.ocs.openshift.io/openshift-storage": ""
