apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: logging
resources:
- ../../base/core/namespaces/openshift-cluster-observability-operator
- ../../base/operators.coreos.com/operatorgroups/openshift-cluster-observability-operator
- ../../base/operators.coreos.com/subscriptions/cluster-observability-operator
