apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  namespace: openshift-config
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
      - names:
          - UPDATE_IN_OVERLAY
        servingCertificate:
          name: default-api-certificate
