apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aitelemetry
labels:
  - includeSelectors: true
    pairs:
      app: aitelemetry
      app.kubernetes.io/name: aitelemetry
resources:
  - site/
  - worker/
  - jobs/
