apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-cluster-management-observability-alertmanager-config
  namespace: open-cluster-management-observability
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: alertmanager-config
    template:
      type: Opaque
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
          route:
            receiver: default
            group_by: [cluster, alertname]
            routes:
              - receiver: slack-notifications
                group_by: [cluster, alertname, namespace, persistentvolumeclaim]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomStoragePersistentVolume.*)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, namespace, instance]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomContainerMemoryUsage)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, namespace, pod, container]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomContainerCpuUsage)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, pool]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomCephStorage.*)"
              - receiver: slack-notifications
                group_by: [cluster, alertname]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomNetworkInterfaceErrors)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, instance]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomIpmi.*)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, node]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomNodeNotReady)"
              - receiver: slack-notifications
                group_by: [cluster, alertname]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "LokiStackWriteRequestErrors|LokiRequestErrors|LokiRequestLatency|NooBaaBucketErrorState|NooBaaResourceErrorState|ClusterOperatorDown|ClusterOperatorDegraded|ClusterOperatorFlapping|ClusterVersionOperatorDown|ClusterMonitoringOperatorReconciliationErrors"
          receivers:
          - name: default
          - name: slack-notifications
            slack_configs:
            - channel: '#alerts-nerc-ocp'
              api_url: "{{ .slack_api_url }}"
              mrkdwn_in:
                - text
                - title
              text: |{{ .slack_config_text }}
              title: "{{ .slack_config_title }}"
              title_link: "{{ .slack_config_title_link }}"
  data:
  - secretKey: slack_api_url
    remoteRef:
      key: nerc/nerc-ocp-infra/open-cluster-management-observability/slack/alerts-nerc-ocp
      property: slack_api_url
  - secretKey: slack_config_text
    remoteRef:
      key: nerc/nerc-ocp-infra/open-cluster-management-observability/slack/alerts-nerc-ocp
      property: slack_config_text
  - secretKey: slack_config_title
    remoteRef:
      key: nerc/nerc-ocp-infra/open-cluster-management-observability/slack/alerts-nerc-ocp
      property: slack_config_title
  - secretKey: slack_config_title_link
    remoteRef:
      key: nerc/nerc-ocp-infra/open-cluster-management-observability/slack/alerts-nerc-ocp
      property: slack_config_title_link
