apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-cluster-management-observability-alertmanager-config
  namespace: open-cluster-management-observability
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: alertmanager-config
    template:
      type: Opaque
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
          route:
            receiver: default
            routes:
              - receiver: slack-notifications
                group_by: [cluster, alertname, namespace, persistentvolumeclaim]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomStoragePersistentVolume.*)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, namespace, instance]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomContainerMemoryUsage)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, namespace, pod, container]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomContainerCpuUsage)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, pool]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomCephStorage.*)"
              - receiver: slack-notifications
                group_by: [cluster, alertname]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomNetworkInterfaceErrors)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, instance]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomIpmi.*)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, node]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomNodeNotReady)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, node]
                group_wait: 1m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomNodeLowAvailableMemory)"
              - receiver: slack-notifications
                group_by: [cluster, alertname]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "LokiStackWriteRequestErrors|LokiRequestErrors|LokiRequestLatency|NooBaaBucketErrorState|NooBaaResourceErrorState|ClusterOperatorDown|ClusterOperatorDegraded|ClusterOperatorFlapping|ClusterVersionOperatorDown|ClusterMonitoringOperatorReconciliationErrors"
              - receiver: slack-notifications-prod-rhods-ope
                group_by: [cluster, alertname, namespace, pod, container]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomOpeLimitsCpu)"
              - receiver: slack-notifications-prod-rhods-ope
                group_by: ['...']
                group_wait: 0s
                # repeat_interval cannot be zero, group_interval cannot be zero
                matchers:
                  - alertname =~ "^Custom(6am|605am)Ope.*"
              - receiver: slack-notifications
                group_by: [cluster, alertname, pool]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(CustomBlockedMachineConfigUpdate|CustomMachineConfigHighUnavailable|CustomMachineConfigPoolDegraded)"
              - receiver: slack-notifications
                group_by: [cluster, alertname, node, deviceid]
                group_wait: 5m
                group_interval: 1d
                repeat_interval: 1d
                matchers:
                  - alertname =~ "(LowPCIeBandwidth|DCGMLevel1Errors|GPUPowerSlowdownEnabled|RemappedRowsActive|DCGMLevel3Errors|PingFailures|PVCAlert|GPUNodeHealth|AutopilotPodsFailing)"

          receivers:
          - name: default
          - name: slack-notifications
            slack_configs:
            - channel: '#alerts-nerc-ocp'
              api_url: "{{ .nerc_ocp_slack_api_url }}"
              mrkdwn_in:
                - text
                - title
              text: |{{ .nerc_ocp_slack_config_text }}
              title: "{{ .nerc_ocp_slack_config_title }}"
              title_link: "{{ .nerc_ocp_slack_config_title_link }}"
          - name: slack-notifications-prod-rhods-ope
            slack_configs:
            - channel: '#alerts-prod-rhods-ope'
              api_url: "{{ .rhods_ope_slack_api_url }}"
              mrkdwn_in:
                - text
                - title
              text: |{{ .rhods_ope_slack_config_text }}
              title: "{{ .rhods_ope_slack_config_title }}"
              title_link: "{{ .rhods_ope_slack_config_title_link }}"
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-infra/open-cluster-management-observability/slack/alerts-nerc-ocp
      rewrite:
        - regexp:
            source: "(.*)"
            target: "nerc_ocp_$1"
    - extract:
        key: nerc/nerc-ocp-infra/open-cluster-management-observability/slack/alerts-prod-rhods-ope
      rewrite:
        - regexp:
            source: "(.*)"
            target: "rhods_ope_$1"
