apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  name: opendatahub-cluster-reader
rules:
  - apiGroups:
      - dashboard.opendatahub.io
    resources:
      - '*'
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - opendatahub.io
    resources:
      - '*'
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - console.openshift.io
    resources:
      - '*'
    verbs:
      - list
      - get
      - watch
