apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: lookup
      name: mss-keycloak
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: ocp-edu      # might need to be changed
        clientSecret:
          name: oauths-clientsecret-nerc
        extraScopes: []
        issuer: https://keycloak.mss.mghpcc.org/auth/realms/mss
      type: OpenID
    - name: github
      mappingMethod: claim
      type: GitHub
      github:
        clientID: <Needs to be added>
        clientSecret:
          name: github-client-secret
        teams:
          - ocp-on-nerc/nerc-ops
