apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: backup-vault
spec:
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  workspaces:
    - name: vault-tls
      mountPath: /vault/tls
    - name: snapshots
      mountPath: /snapshots
    - name: backup-job
      mountPath: /backup-job
    - name: backup-scripts
      mountPath: /scripts
  steps:
    - name: create-snapshot
      image: docker.io/hashicorp/vault:1.15.5
      workingDir: /workspace
      env:
        - name: VAULT_CACERT
          value: /vault/tls/ca.crt
        - name: VAULT_ADDR
          value: https://vault:8200
        - name: SNAPSHOT_PATH
          value: $(workspaces.snapshots.path)
      script: |
        #!/bin/sh
        exec sh /scripts/create-snapshot.sh

    - name: backup-snapshot-to-s3
      image: docker.io/minio/mc:RELEASE.2024-02-09T22-18-24Z
      workingDir: /workspace
      envFrom:
        - secretRef:
            name: vault-backup-s3-endpoint
        - configMapRef:
            name: vault-backup-config
      env:
        - name: SNAPSHOT_PATH
          value: $(workspaces.snapshots.path)
      script: |
        #!/bin/sh
        exec bash /scripts/backup-to-s3.sh

    - name: cleanup-old-taskruns
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      workingDir: /workspace
      envFrom:
        - configMapRef:
            name: vault-backup-config
      env:
        - name: TASK_NAME
          value: $(context.task.name)
      script: |
        #!/bin/sh
        exec bash /scripts/cleanup-taskruns.sh
