apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  mig:
    strategy: single
  migManager:
    config:
      default: all-disabled
      name: test-mig-parted-config
  daemonsets:
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: NVIDIA-A100-SXM4-40GB
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: Tesla-V100-PCIE-32GB
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: NVIDIA-H100-80GB-HBM3
