apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  mig:
    strategy: single
  migManager:
    config:
      default: all-disabled
      name: test-mig-parted-config
  driver:
    enabled: false
    upgradePolicy:
      autoUpgrade: true
      drain:
        deleteEmptyDir: true
        enable: true
        force: true
        timeoutSeconds: 300
      maxParallelUpgrades: 1
      maxUnavailable: 25%
      podDeletion:
        deleteEmptyDir: true
        force: true
        timeoutSeconds: 300
      waitForCompletion:
        timeoutSeconds: 0
    useNvidiaDriverCRD: true
  daemonsets:
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: NVIDIA-A100-SXM4-40GB
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: Tesla-V100-PCIE-32GB
    - effect: NoSchedule
      key: nvidia.com/gpu.product
      operator: Equal
      value: NVIDIA-H100-80GB-HBM3
