apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: nerc-cluster-secrets
spec:
  provider:
    vault:
      caProvider:
        type: "Secret"
        namespace: "external-secrets-operator"
        name: "vault-tls"
        key: "ca.crt"
      server: https://vault.vault.svc.cluster.local:8200
      auth:
        kubernetes:
          mountPath: kubernetes/nerc-ocp-infra/
