apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: operator
  name: ibm-spectrum-scale-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: ibm-spectrum-scale-webhook-service
      namespace: ibm-spectrum-scale-operator
      path: /mutate-scale-spectrum-ibm-com-v1beta1-cluster
  failurePolicy: Fail
  name: mcluster.scale.spectrum.ibm.com
  rules:
  - apiGroups:
    - scale.spectrum.ibm.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: ibm-spectrum-scale-webhook-service
      namespace: ibm-spectrum-scale-operator
      path: /mutate-scale-spectrum-ibm-com-v1beta1-filesystem
  failurePolicy: Ignore
  name: mfilesystem.scale.spectrum.ibm.com
  rules:
  - apiGroups:
    - scale.spectrum.ibm.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - filesystems
  sideEffects: None
