apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- solrbackups.yaml
- solrclouds.yaml
- solrprometheusexporters.yaml
- zookeeperclusters.yaml
labels:
- includeSelectors: true
  pairs:
    nerc.mghpcc.org/bundle: solr-helm-repo
