apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: postgres
spec:
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 50Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
      replicas: 3
      name: 'postgres'
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-15.1-3.3-0
  postgresVersion: 15
  openshift: true
  postGISVersion: 3.3.0
  users:
    - name: keycloak
      options: "SUPERUSER"
      databases:
        - keycloak
    - name: aitelemetry
      options: "SUPERUSER"
      databases:
        - aitelemetry
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host keycloak keycloak all md5"
          - "local keycloak keycloak trust"
          - "host aitelemetry aitelemetry all md5"
          - "local aitelemetry aitelemetry trust"
