apiVersion: nvidia.com/v1alpha1
kind: NVIDIADriver
metadata:
  name: volta
spec:
  driverType: "gpu"
  image: "driver"
  repository: "nvcr.io/nvidia"
  version: "580.105.08"
  kernelModuleType: "auto"
  rdma:
    enabled: false
  nodeSelector:
    feature.node.kubernetes.io/nvidia-gpu.product: Tesla-V100-PCIE-32GB
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu.product
    operator: Equal
    value: Tesla-V100-PCIE-32GB
