aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        nerc.mghpcc.org/aggregate-to-nerc-ops: "true"
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-admin: "true"
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-view: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kruize-admins
