apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: logsarchive-backing-store
  namespace: openshift-storage
spec:
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: 50Ti
    storageClass: ocs-external-storagecluster-ceph-rbd
  type: pv-pool
