apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/operators.coreos.com/subscriptions/gatekeeper-operator
labels:
- includeSelectors: true
  pairs:
    nerc.mghpcc.org/bundle: gatekeeper
