apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../base/external-secrets.io/externalsecrets/custom-login-templates
  - console

patches:
  - patch: |
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        templates:
          providerSelection:
            name: custom-login-templates
