kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: prom-keycloak-proxy
spec:
  host: REPLACE_IN_OVERLAY
  to:
    kind: Service
    name: REPLACE_IN_OVERLAY
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
