apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
resources:
- deployments
- externalsecrets
- routes
- secrets
- serviceaccounts
- services
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: dex
    app.kubernetes.io/part-of: auth
