apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
  labels:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: solr
    app.kubernetes.io/component: solr
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: solr
      app.kubernetes.io/name: solr
      app.kubernetes.io/component: solr
  serviceName: solr-headless
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: solr
        app.kubernetes.io/name: solr
        app.kubernetes.io/component: solr
    spec:
      serviceAccountName: solr
      automountServiceAccountToken: false
      affinity:
        podAffinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: solr
                    app.kubernetes.io/name: solr
                    app.kubernetes.io/component: solr
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
      enableServiceLinks: true
      initContainers:
        - name: prepare-server-dir
          image: docker.io/bitnamilegacy/solr:9.7.0-debian-12-r0
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 2Gi
              memory: 2Gi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          command:
            - /bin/bash
          args:
            - -ec
            - |
              #!/bin/bash
              . /opt/bitnami/scripts/liblog.sh
              info "Copying server dir to empty dir"
              # In order to not break the application functionality (such as upgrades or plugins) we need
              # to make the base directory writable, so we need to copy it to an empty dir volume
              cp -r --preserve=mode /opt/bitnami/solr/server /emptydir/app-server-dir
              info "Copy operation completed"
          volumeMounts:
            - name: empty-dir
              mountPath: /emptydir
      containers:
        - name: solr
          image: docker.io/bitnami/solr:9.7.0-debian-12-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          command:
            - /scripts/setup.sh
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SOLR_ENABLE_CLOUD_MODE
              value: "yes"
            - name: SOLR_NUMBER_OF_NODES
              value: "3"
            - name: SOLR_PORT_NUMBER
              value: "8983"
            - name: SOLR_SERVER_DIRECTORY
              value: "server"
            - name: SOLR_COLLECTION
              value: "my-collection"
            - name: SOLR_COLLECTION_SHARDS
              value: "3"
            - name: SOLR_COLLECTION_REPLICAS
              value: "1"
            - name: SOLR_ENABLE_AUTHENTICATION
              value: "yes"
            - name: SOLR_ADMIN_USERNAME
              value: "admin"
            - name: SOLR_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: solr-secret
                  key: solr-password
            - name: SOLR_ZK_HOSTS
              value: "zookeeper.zookeeper.svc:2181"
          ports:
            - name: http
              containerPort: 8983
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 2Gi
              memory: 3Gi
            requests:
              cpu: 850m
              ephemeral-storage: 50Mi
              memory: 1Gi
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
            exec:
              command:
              - /bin/bash
              - -ec
              - |
                curl --silent --connect-timeout 15000 --user ${SOLR_ADMIN_USERNAME}:${SOLR_ADMIN_PASSWORD} http://localhost:${SOLR_PORT_NUMBER}/solr/admin/info/system | grep --quiet  '\"status\":0'
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
            exec:
              command:
              - /bin/bash
              - -ec
              - |
                curl --silent --connect-timeout 15000 --user ${SOLR_ADMIN_USERNAME}:${SOLR_ADMIN_PASSWORD} http://localhost:${SOLR_PORT_NUMBER}/api/node/health | grep --quiet  '\"status\":\"OK\"'
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/solr/server
              subPath: app-server-dir
            - name: empty-dir
              mountPath: /opt/bitnami/solr/logs
              subPath: app-logs-dir
            - name: empty-dir
              mountPath: /opt/bitnami/solr/tmp
              subPath: app-tmp-dir
            - name: scripts
              mountPath: /scripts/setup.sh
              subPath: setup.sh
            - name: data
              mountPath: /bitnami/solr
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: scripts
          configMap:
            name: solr-scripts
            defaultMode: 0755
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "50Gi"
