kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: oauth-proxy
  namespace: redhat-ods-applications
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4bef31eb993feb6f1096b51b4876c65a6fb1f4401fee97fa4f4542b6b7c9bc46'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
