apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solr-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - solr.apache.org
  resources:
  - "*"
  verbs:
  - "*"
