apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: loki-app
      type: loki
      url: https://logging-loki-openshift-logging.apps.obs.nerc.mghpcc.org/api/logs/v1/application
      secret:
        name: lokistack-gateway-bearer-token
    - name: loki-infra
      type: loki
      url: https://logging-loki-openshift-logging.apps.obs.nerc.mghpcc.org/api/logs/v1/infrastructure
      secret:
        name: lokistack-gateway-bearer-token
    - name: loki-audit
      type: loki
      url: https://logging-loki-openshift-logging.apps.obs.nerc.mghpcc.org/api/logs/v1/audit
      secret:
        name: lokistack-gateway-bearer-token
  pipelines:
    - name: send-app-logs
      inputRefs:
        - application
      outputRefs:
        - loki-app
    - name: send-infra-logs
      inputRefs:
        - infrastructure
      outputRefs:
        - loki-infra
    - name: send-audit-logs
      inputRefs:
        - audit
      outputRefs:
        - loki-audit
