---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zookeeper-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
