apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: disable-net-ifnames-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
    - net.ifnames=0
    - biosdevname=0
