apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: nerc-secret-store
spec:
  provider:
    vault:
      server: "https://vault-ui-vault.apps.infra.nerc.mghpcc.org/"
      path: "nerc"
      version: "v2"
      auth:
        kubernetes:
          mountPath: UPDATE IN OVERLAY
          role: secret-reader
          secretRef:
            name: "vault-secret-reader"
            key: "token"
