apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  limits:
    global:
      ingestion:
        ingestionBurstSize: 20
        ingestionRate: 20
        perStreamRateLimit: 20
        perStreamRateLimitBurst: 20
      retention:
        days: 90
    tenants:
      audit:
        retention:
          days: 90
      application:
        retention:
          days: 30
      infrastructure:
        retention:
          days: 30
  managementState: Managed
  storage:
    schemas:
    - effectiveDate: '2020-10-11'
      version: v11
    - effectiveDate: '2025-11-01'
      version: v12
    - effectiveDate: '2025-11-15'
      version: v13
    secret:
      name: thanos-object-storage
      type: s3
  tenants:
    mode: openshift-logging
    openshift:
      adminGroups:
      - nerc-logs-metrics
  size: 1x.medium
  storageClassName: ocs-external-storagecluster-ceph-rbd
