apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret
spec:
  data:
  - remoteRef:
      key: REPLACE_IN_OVERLAY
      property: pull-secret
    secretKey: .dockerconfigjson
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nerc-cluster-secrets
  target:
    name: pull-secret
