apiVersion: v1
data:
  ROOK_CSI_ENABLE_CEPHFS: "true"
  ROOK_LOG_LEVEL: DEBUG
  CSI_PLUGIN_TOLERATIONS: |2-

    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
    - key: nvidia.com/gpu.product
      operator: Equal
      value: "Tesla-V100-PCIE-32GB"
      effect: NoSchedule
    - key: nvidia.com/gpu.product
      operator: Equal
      value: "NVIDIA-A100-SXM4-40GB"
      effect: NoSchedule
  CSI_PROVISIONER_TOLERATIONS: |2-

    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
    - key: nvidia.com/gpu.product
      operator: Equal
      value: "Tesla-V100-PCIE-32GB"
      effect: NoSchedule
    - key: nvidia.com/gpu.product
      operator: Equal
      value: "NVIDIA-A100-SXM4-40GB"
      effect: NoSchedule
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
