apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: kubernetes-nmstate-operator
spec:
    channel: "4.10"
    installPlanApproval: Automatic
    name: kubernetes-nmstate-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
