apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    name: version
  spec:
    channel: stable-4.19
    clusterID: 090f2819-f1b3-4f72-bc6f-dc149ced3083
kind: List
metadata: {}
